project:
  type: website
  output-dir: docs

website:
    navbar:
      left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - Publications.qmd
      - Posts.qmd
      - Tutorial.qmd
      right:
      - text: get in touch!
        menu:
          - icon: twitter
            text: Twitter
            href: https://twitter.com/nipun_shrestha
          - icon: linkedin
            text: Linkedin
            href: https://www.linkedin.com/in/nipun-shrestha-a4903887/
          - icon: envelope
            text: Email
            href: mailto:drnipunsth@gmail.com
      tools: 
      - icon: github
        text: Github
        href: https://github.com/Nipun-Shrestha
    page-footer:
      center: |
        <span class="container"><strong>[Contact Nipun Shrestha](mailto:drnipunsth@gmail.com){target="_blank"}</strong></span>
      left: |
        <span class="container"><strong>Made with [Posit Quarto](https://quarto.org/){target="_blank"}</strong></span>
      right: |
        <span class="container"><strong>[Github Repo](https://github.com/Nipun-Shrestha/Profile_page){target="_blank"}</strong></span>
      background: "#306A9E"
twitter-card: true
open-graph: true

google-analytics: 
  tracking-id: "G-EY5KG3VY2K"
  cookie-consent: true
  anonymize-ip: true

format:
  html:
    theme: 
      cosmo
      styles.scss
      mainfont:Nunito Sans
    include-in-header:
      - text: |
          <meta name="google-site-verification" content="2yr2KIypX7Kvr8Hn1g1YojGA6ZipA8o6h-3daP-uNGQ" />
    toc: true
editor: visual
